### ISSUE TITLE
Redstone issues

### ISSUE THREAD

**Issue by ApocalypticWanderer** [phil14052/CustomCobbleGen#12]
When using a "Normal" cobble gen it works great. But as soon as I add a Redstone contraption to push away the block away it'll only spawn cobblestone.

**Comment by phil14052** [comment]
Hi, 
The system works so when a player breaks a block that is generated by a cobblestone generator, then it puts it into short term memory. This means that when the new block is generated by the plugin, it has already deleted the player information. This makes the plugin more lightweight and for some servers, this is more ideal since it disables automation of cobblestone generators.

Would you want me to look into a feature to enable automation, but this will lead to some disadvantages?

- Phil

**Comment by ApocalypticWanderer** [comment]
If there would be a way to enable/disable this feature in the config then that would be great. Then people can decide which one they want. :D
