### ISSUE TITLE
the generator is not working

### ISSUE THREAD

**Issue by Eur0x** [phil14052/CustomCobbleGen#30]
**Describe the bug**

after installation, nothing has changed, the stone is not replaced with ores - from generator
(plugin is fresh after install)

**Console errors**

empty

**Config file**

https://hastebin.com/fekelitewo.php

**System (please complete the following information):**

 - OS: [Win_10]
 - Plugin version: [1.4.1]
 - MC version: [1.15.2] - latest spigot jar

**Comment by phil14052** [comment]
Sorry for the late answer. I do not know why I have not responsed to this.
It looks like you are testing it in a world called "world" which is on the disabled worlds lists by default in version 1.4.1. If you test it in another world or remove that world from the disabled worlds list then it will probably work again.
In the next version this will never happen because I will remove it by default :D
