### ISSUE TITLE
something don't right

### ISSUE THREAD

**Issue by thebladeofflame** [phil14052/CustomCobbleGen#43]
![image](https://user-images.githubusercontent.com/58851040/104837809-ef4b8a80-58f1-11eb-819a-9446396d5884.png)
[config.zip](https://github.com/phil14052/CustomCobbleGen/files/5825871/config.zip)
        STONE: 63.8
        COAL_ORE: 20
        IRON_ORE: 12.5
        GOLD_ORE: 2
        REDSTONE_ORE: 0.6
        LAPIS_ORE: 0.6
        DIAMOND_ORE: 0.2
        EMERALD_ORE: 0.2
        ANCIENT_DEBRIS: 0.1
I'm sure these options  add up to 100.
But when I reload CustomCobbleGen, CustomCobbleGen will report  ser error - Results total percentage is under 100% in the 高级Lv2 tier. Total percentage = 99.99999999999999"
server version: 1.16.4 (Paper version git-Paper-394)
plugins version: CustomCobbleGen v1.4.5
system version: CentOS 7

Sorry for my bad English.

**Comment by phil14052** [comment]
You are correct. Java can sometimes miscalculate with 0.0000000001 so that is why it is giving this warning. This is a warning and not an error so the plugin works without problems 99.99999999999% of the time with this configuration.
In the next version, I will put a buffer on this warning. Just ignore this. The plugin should work :D
